name: shiv_wallpaper
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_mobile_ads: ^3.0.0  
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  cloud_firestore: ^4.8.0
  flutter_wallpaper_manager: ^0.0.4
  flutter_cache_manager:
  internet_connection_checker: ^1.0.0+1
  overlay_support: ^2.1.0
  url_launcher: ^6.1.0
  share:
  image_gallery_saver: ^2.0.3
  dio: ^5.3.2
  permission_handler: ^11.0.0
  cached_network_image: ^3.0.0
  firebase_messaging: ^14.1.0

#new
  hooks_riverpod: ^2.4.0
  go_router: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/Logo.png"


flutter:


  uses-material-design: true
 # - assets/logo.png
